### PR TITLE
Fix a couple of issues with Python 3 and add debug messages

### PR DESCRIPTION
**Pull request by techtonik**

### CODE REVIEW

**Comment by techtonik** [comment]
There will be more fixes coming.

**Comment by cessen** [comment]
Hi techtonik,
This all looks really great to me, and I would love to merge it.

Except I'm not sure what gains we get right now from the Tool class over just using strings.  If in the future we end up wanting a distinction between the name and executable of the tool, then we can migrate to something like that.  But until we're ready to actually take advantage of the functionality, I think all it does is complicate the code.

So could you remove that one change?  Everything else looks great.

Thanks!

**Comment by techtonik** [comment]
Yes, the Tool class is not ready yet.. but it helped me a bit to juggle with structure. I can;t just stand those global variables. Let me see if it is possible to rebase this.

**Comment by techtonik** [comment]
Looks like I've messed things up.

**Comment by techtonik** [comment]
Done. But this needs to be tested.

**Comment by cessen** [comment]
What part of this still needs to be tested?  Have you tested it on your machine?

**Comment by techtonik** [comment]
@cessen this just needs to be run on Linux, because I am testing this on Windows.

**Comment by techtonik** [comment]
The test plan.

##### shows help with -h
* [ ] Windows
* [ ] Linux

##### captures whole help without params
* [ ] Windows
* [ ] Linux

**Comment by techtonik** [comment]
@cessen it is tested and can be merged now. Please take a look.

**Comment by techtonik** [comment]
@cessen ping?

**Comment by techtonik** [comment]
@cessen what else is required to make the merged?

**Comment by cessen** [comment]
Ah!  I am so sorry.  I am being a terrible project steward. :-(

Merging now.  Thanks so much for your contribution!

**Comment by techtonik** [comment]
@cessen I understand the pressure - I am a terrible steward myself. =) Thanks!

**Pull request merged**
